export const shoeImageMap: { [key: string]: string } = {
    'Five Ten Team': '/5.10Team.jpg',
    'Butora Acro Female': '/acroF.jpg',
    'Butora Acro Male': '/acroM.webp',
    'Evolv Addict': '/addict.jpg',
    'Butora Altura': '/altura.webp',
    'Five Ten Anasazi Female': '/anasaziF.jpg',
    'Five Ten Anasazi Male': '/anasaziM.jpg',
    'Evolv Astroman': '/astroman.jpg',
    'Scarpa Chimera': '/chimera.jpg',
    'La Sportiva Cobra': '/cobra.jpg',
    'Evolv Defy Female': '/defyF.webp',
    'Evolv Defy Male': '/defyM.jpg',
    'Scarpa Drago Female': '/dragoF.jpg',
    'Scarpa Drago Male': '/dragoM.jpg',
    'Five Ten Dragon': '/dragon.jpg',
    'Butora Endeavor Female': '/endeavorF.webp',
    'Butora Endeavor Male': '/endeavorM.webp',
    'Scarpa Furia': '/furia.jpg',
    'Scarpa Furia S': '/furiaS.jpg',
    'Evolv Geshido Female': '/geshidoF.webp',
    'Evolv Geshido Male': '/geshidoM.webp',
    'Five Ten Grandstone': '/grandstone.jpg',
    'Scarpa Helix Female': '/helixF.avif',
    'Scarpa Helix Male': '/helixM.avif',
    'Five Ten Hiangle Female': '/hiangleF.jpg',
    'Five Ten Hiangle Male': '/hiangleM.jpeg',
    'Scarpa Instinct Female': '/instinctF.webp',
    'Scarpa Instinct Male': '/instinctM.jpg',
    'Scarpa Instinct VSR': '/instinctVSR.jpg',
    'La Sportiva Kataki': '/kataki.jpg',
    'La Sportiva Katana Female': '/katanaF.avif',
    'La Sportiva Katana Male': '/katanaM.webp',
    'Butora Kira': '/kira.jpg',
    'Evolv Kronos Male': '/kronosM.webp',
    'Scarpa Maestro': '/maestro.jpeg',
    'La Sportiva Maverink': '/mavernik.jpg',
    'La Sportiva Miura Female': '/miuraF.jpg',
    'La Sportiva Miura Male': '/miuraM.jpg',
    'Five Ten Moccasym': '/moccasym.jpg',
    'Black Diamond Momentum Female': '/momentumF.jpg',
    'Black Diamond Momentum Male': '/momentumM.avif',
    'La Sportiva Otaki': '/otaki.jpg',
    'Evolv Phantom': '/phantom.webp',
    'La Sportiva Python': '/python.jpg',
    'Five Ten Rogue Female': '/rogueF.jpg',
    'Five Ten Rogue Male': '/rogueM.jpg',
    'Evolv Shakra': '/shakra.jpg',
    'Evolv Shaman Female': '/shamanF.webp',
    'Evolv Shaman Male': '/shamanM.jpg',
    'La Sportiva Solution Female': '/solutionF.jpg',
    'La Sportiva Solution Male': '/solutionM.jpg',
    'La Sportiva Tarantulace Female': '/tarantulaceF.jpg',
    'La Sportiva Tarantulace Male': '/tarantulaceM.jpg',
    'La Sportiva TC Pro': '/tcpro.jpg',
    'La Sportiva Testarossa': '/testarossaM.jpg',
    'Scarpa Vapor Female': '/vaporF.jpg',
    'Scarpa Vapor Male': '/vaporM.jpg',
    'Evolv Zenist': '/zenist.jpg'
};
