export const shoeImageMap: { [key: string]: string } = {
    'Five Ten Team': '/shoeSelection/5.10Team.jpg',
    'Butora Acro Female': '/shoeSelection/acroF.jpg',
    'Butora Acro Male': '/shoeSelection/acroM.webp',
    'Evolv Addict': '/shoeSelection/addict.jpg',
    'Butora Altura': '/shoeSelection/altura.webp',
    'Five Ten Anasazi Female': '/shoeSelection/anasaziF.jpg',
    'Five Ten Anasazi Male': '/shoeSelection/anasaziM.jpg',
    'Evolv Astroman': '/shoeSelection/astroman.jpg',
    'Scarpa Chimera': '/shoeSelection/chimera.jpg',
    'La Sportiva Cobra': '/shoeSelection/cobra.jpg',
    'Evolv Defy Female': '/shoeSelection/defyF.webp',
    'Evolv Defy Male': '/shoeSelection/defyM.jpg',
    'Scarpa Drago Female': '/shoeSelection/dragoF.jpg',
    'Scarpa Drago Male': '/shoeSelection/dragoM.jpg',
    'Five Ten Dragon': '/shoeSelection/dragon.jpg',
    'Butora Endeavor Female': '/shoeSelection/endeavorF.webp',
    'Butora Endeavor Male': '/shoeSelection/endeavorM.webp',
    'Scarpa Furia': '/shoeSelection/furia.jpg',
    'Scarpa Furia S': '/shoeSelection/furiaS.jpg',
    'Evolv Geshido Female': '/shoeSelection/geshidoF.webp',
    'Evolv Geshido Male': '/shoeSelection/geshidoM.webp',
    'Five Ten Grandstone': '/shoeSelection/grandstone.jpg',
    'Scarpa Helix Female': '/shoeSelection/helixF.avif',
    'Scarpa Helix Male': '/shoeSelection/helixM.avif',
    'Five Ten Hiangle Female': '/shoeSelection/hiangleF.jpg',
    'Five Ten Hiangle Male': '/shoeSelection/hiangleM.jpeg',
    'Scarpa Instinct VS Female': '/shoeSelection/instinctF.webp',
    'Scarpa Instinct VS': '/shoeSelection/instinctM.jpg',
    'Scarpa Instinct VSR': '/shoeSelection/instinctVSR.jpg',
    'La Sportiva Kataki': '/shoeSelection/kataki.jpg',
    'La Sportiva Katana Female': '/shoeSelection/katanaF.avif',
    'La Sportiva Katana Male': '/shoeSelection/katanaM.webp',
    'Butora Kira': '/shoeSelection/kira.jpg',
    'Evolv Kronos Male': '/shoeSelection/kronosM.webp',
    'Scarpa Maestro': '/shoeSelection/maestro.jpeg',
    'La Sportiva Maverink': '/shoeSelection/mavernik.jpg',
    'La Sportiva Miura Female': '/shoeSelection/miuraF.jpg',
    'La Sportiva Miura Male': '/shoeSelection/miuraM.jpg',
    'Five Ten Moccasym': '/shoeSelection/moccasym.jpg',
    'Black Diamond Momentum Female': '/shoeSelection/momentumF.jpg',
    'Black Diamond Momentum Male': '/shoeSelection/momentumM.avif',
    'La Sportiva Otaki': '/shoeSelection/otaki.jpg',
    'Evolv Phantom': '/shoeSelection/phantom.webp',
    'La Sportiva Python': '/shoeSelection/python.jpg',
    'Five Ten Rogue Female': '/shoeSelection/rogueF.jpg',
    'Five Ten Rogue Male': '/shoeSelection/rogueM.jpg',
    'Evolv Shakra': '/shoeSelection/shakra.jpg',
    'Evolv Shaman Female': '/shoeSelection/shamanF.webp',
    'Evolv Shaman Male': '/shoeSelection/shamanM.jpg',
    'La Sportiva Solution Female': '/shoeSelection/solutionF.jpg',
    'La Sportiva Solution Male': '/shoeSelection/solutionM.jpg',
    'La Sportiva Tarantulace Female': '/shoeSelection/tarantulaceF.jpg',
    'La Sportiva Tarantulace Male': '/shoeSelection/tarantulaceM.jpg',
    'La Sportiva TC Pro': '/shoeSelection/tcpro.jpg',
    'La Sportiva Testarossa': '/shoeSelection/testarossaM.jpg',
    'Scarpa Vapor Female': '/shoeSelection/vaporF.jpg',
    'Scarpa Vapor Male': '/shoeSelection/vaporM.jpg',
    'Evolv Zenist': '/shoeSelection/zenist.jpg'
};
